name: LibD
options:
  bundleIdPrefix: com.myapp.LibD
projectReferences:
  LibE:
    path: ../LibE/LibE.xcodeproj
settings:
  configs:
    debug:
      SWIFT_COMPILATION_MODE: wholemodule
    release:
      SWIFT_COMPILATION_MODE: wholemodule
targets:
  LibD:
    type: library.static
    platform: iOS
    sources: [Sources]
    dependencies:
      - target: LibE/LibE